# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from chrome_cache.cache import Browser


user = os.environ['USERPROFILE']
path = os.path.join(
    user, 'AppData/Local/Google/Chrome/User Data/Default/Cache')

chrome_cache = Browser.Chrome.Cache.file_open(path)
cache = chrome_cache.get_all_info()
cache_len = len(cache)

file_path = []
creation_time = []
last_modified_time = []
access_time = []
file_name = []
file_size = []
url = []
cache_count = 0
for i in cache:
    # print(i)
    file_path.insert(cache_count, i['file_path'])
    creation_time.insert(cache_count, i['creation_time'])
    if i['last_modified_time'] == '1601-01-01 00:00:00':
        i['last_modified_time'] = ''
    last_modified_time.insert(cache_count, i['last_modified_time'])
    access_time.insert(cache_count, i['access_time'])
    file_name.insert(cache_count,i['file_name'])
    file_size.insert(cache_count, i['file_size'])
    url.insert(cache_count, i['url'])
    cache_count += 1

#print(file_path)
#print(creation_time)
#print(last_modified_time)
#print(access_time)
#print(file_name)
#print(file_size)
#print(url)