# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinkFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, tab,tapname_list):

        self.gridLayout_5 = QtWidgets.QGridLayout(tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()

        self.Chrome_Detail = QtWidgets.QTableWidget(tab)
        self.gridLayout_5.addWidget(self.Chrome_Detail, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.Chrome_Detail.setRowCount(13)
        self.Chrome_Detail.setObjectName("Chrome_Detail")
        self.Chrome_Detail.setColumnCount(1)

        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setVerticalHeaderItem(12, item)

        item = QtWidgets.QTableWidgetItem()
        self.Chrome_Detail.setColumnWidth(0, 300)
        tapname_list.append(self.Chrome_Detail.objectName())
        self.Chrome_Detail.setHorizontalHeaderItem(0, item)
        self.Chrome_Label = QtWidgets.QLabel(tab)
        self.Chrome_Label.setGeometry(QtCore.QRect(20, 10, 261, 41))
        self.Chrome_Detail.setVerticalHeaderLabels(
            ["사용 웹 브라우저", "로컬 열람 파일 이름", "로컬 파일 열람 시각", "다운로드 파일 이름", "다운로드 시각", "사이트 접속 주소",
             "사이트 접속 시각", "캐시 파일 이름", "캐시 파일 경로", "캐시 열람 시각", "캐시 파일 크기", "캐시 수정 시각", "캐시 URL"])
        self.Chrome_Detail.setHorizontalHeaderLabels(["데이터"])
        header = self.Chrome_Detail.horizontalHeader()
        self.Chrome_Detail.setSortingEnabled(True)
        self.Chrome_Detail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Chrome_Detail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Chrome_Detail.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.Chrome_Detail.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)
        self.Chrome_Detail.setAutoScroll(True)
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header_ver = self.Chrome_Detail.verticalHeader()
        for i in range(0, self.Chrome_Detail.rowCount()):
            header_ver.setSectionResizeMode(i, QtWidgets.QHeaderView.Stretch)
    def update(self):
        self.Chrome_Detail.update()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())