# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinkFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, tab,tapname_list):

        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setBold(False)
        font.setWeight(50)
        font.setPointSize(9)

        font1 = QtGui.QFont()
        font1.setFamily("Agency FB")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)

        self.gridLayout_5 = QtWidgets.QGridLayout(tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()

        self.Continuous_Detail = QtWidgets.QTableWidget(tab)
        self.Continuous_Detail.setObjectName("Continuous_Detail")
        self.gridLayout_5.addWidget(self.Continuous_Detail, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.Continuous_Detail.setFont(font)
        self.Continuous_Detail.setMouseTracking(False)
        self.Continuous_Detail.setTabletTracking(False)
        self.Continuous_Detail.setAcceptDrops(False)
        self.Continuous_Detail.setToolTipDuration(-1)
        self.Continuous_Detail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Continuous_Detail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)  # 가로스크롤
        self.Continuous_Detail.setAutoScroll(True)
        self.Continuous_Detail.setAutoScrollMargin(16)
        self.Continuous_Detail.setSortingEnabled(True)
        self.Continuous_Detail.setShowGrid(True)
        self.Continuous_Detail.setRowCount(0)
        self.Continuous_Detail.setColumnCount(4)
        self.Continuous_Detail.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)  # Options : Not Edit
        self.Continuous_Detail.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Continuous_Detail.setHorizontalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Continuous_Detail.setHorizontalHeaderItem(1, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Continuous_Detail.setHorizontalHeaderItem(2, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Continuous_Detail.setHorizontalHeaderItem(3, item)

        self.Continuous_Detail.setHorizontalHeaderLabels(["File Name", "File Path", "Last Run Time", "Artifacts"])
        tapname_list.append(self.Continuous_Detail.objectName())
        header = self.Continuous_Detail.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        for i in range(1, self.Continuous_Detail.columnCount() - 1):
            header.setSectionResizeMode(i, QtWidgets.QHeaderView.ResizeToContents)

    def rowCount(self,number):
        self.Continuous_Detail.setRowCount(number)

    def update(self):
        self.Continuous_Detail.update()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
