# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5 import QtCore, QtGui, QtWidgets


from winreg import *
from D_check import realDeleted, check2

class Ui_Dialog(object):



    def __init__(self):
        self.net = "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\AppCompatCache"  # 서브레지스트리 목록 지정 ( ShimCache 경로 )
        self.reg = ConnectRegistry(None, HKEY_LOCAL_MACHINE)  # 루트 레지스트리 핸들 객체 얻기
        self.key = OpenKey(self.reg, self.net)  # 레지스트리 핸들 객체 얻기

        self.a, self.b, self.c = EnumValue(self.key, 0)  # 지정한 레지스트리 하위 키값 조회
        self.bin_size = len(self.b)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1140, 870) #전체 창 크기(가로,세로)
        Dialog.setAutoFillBackground(False)

        self.ListTable = QtWidgets.QTableWidget(Dialog)
        self.ListTable.setGeometry(QtCore.QRect(30, 140, 1080, 700)) #데이터 창 크기(왼쪽여백,위쪽여백,가로,세로)
        self.ListTable.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.ListTable.setSizeIncrement(QtCore.QSize(0, 0))
        self.ListTable.setBaseSize(QtCore.QSize(0, 0))

        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setBold(False)
        font.setWeight(50)
        font.setPointSize(9)

        font1 = QtGui.QFont()
        font1.setFamily("Agency FB")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)

        s = self.Defile()
        self.ListTable.setFont(font)
        self.ListTable.setMouseTracking(False)
        self.ListTable.setTabletTracking(False)
        self.ListTable.setAcceptDrops(False)
        self.ListTable.setToolTipDuration(-1)
        self.ListTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ListTable.setAutoScroll(True)
        self.ListTable.setAutoScrollMargin(16)
        self.ListTable.setShowGrid(True)
        self.ListTable.setRowCount(s - 1)
        self.ListTable.setColumnCount(4)
        self.ListTable.setObjectName("ListTable")


        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.ListTable.setHorizontalHeaderItem(0, item)
        self.ListTable.setColumnWidth(0, 200)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        item.setFont(font)
        self.ListTable.setHorizontalHeaderItem(1, item)
        self.ListTable.setColumnWidth(1, 400)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        item.setFont(font)
        self.ListTable.setHorizontalHeaderItem(2, item)
        self.ListTable.setColumnWidth(2, 200)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.ListTable.setHorizontalHeaderItem(3, item)
        self.ListTable.setColumnWidth(3, 200)

        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(28, 5, 80, 30))#저장 버튼
        self.saveButton.setObjectName("saveButton")

        self.Category = QtWidgets.QComboBox(Dialog)
        self.Category.setGeometry(QtCore.QRect(161, 40, 120, 25))#검색기준2(파일명) 콤보박스
        self.Category.setObjectName("Category")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")

        self.SettingTime_2 = QtWidgets.QLabel(Dialog)
        self.SettingTime_2.setGeometry(QtCore.QRect(30, 70, 120, 20))#"파일크기 (KB)"
        self.SettingTime_2.setFont(font1)
        self.SettingTime_2.setObjectName("SettingTime_2")

        self.SettingTime2 = QtWidgets.QLabel(Dialog)
        self.SettingTime2.setGeometry(QtCore.QRect(398, 107, 16, 16))#"~"
        self.SettingTime2.setFont(font)
        self.SettingTime2.setObjectName("SettingTime2")

        self.SearchButton = QtWidgets.QPushButton(Dialog)
        self.SearchButton.setGeometry(QtCore.QRect(660, 40, 75, 26))#Search 버튼
        self.SearchButton.setCheckable(True)
        self.SearchButton.setChecked(True)
        self.SearchButton.setObjectName("SearchButton")

        self.FileSize = QtWidgets.QLineEdit(Dialog)
        self.FileSize.setGeometry(QtCore.QRect(160, 70, 230, 25))#파일크기 박스
        self.FileSize.setObjectName("FileSize")

        self.StartTime = QtWidgets.QDateTimeEdit(Dialog)
        self.StartTime.setGeometry(QtCore.QRect(160, 100, 230, 25))#시간설정1 박스
        self.StartTime.setDateTime(QtCore.QDateTime.currentDateTime())
        self.StartTime.setCalendarPopup(True)
        self.StartTime.setObjectName("StartTime")

        self.EndTime = QtWidgets.QDateTimeEdit(Dialog)
        self.EndTime.setGeometry(QtCore.QRect(420, 100, 230, 25))#시간설정2 박스
        self.EndTime.setDateTime(QtCore.QDateTime.currentDateTime())
        self.EndTime.setCalendarPopup(True)
        self.EndTime.setObjectName("EndTime")

        self.Artifacts = QtWidgets.QComboBox(Dialog)
        self.Artifacts.setGeometry(QtCore.QRect(30, 40, 120, 25))#검색기준1(아티팩트) 콤보박스
        self.Artifacts.setObjectName("Artifacts")
        self.Artifacts.addItem("")
        self.Artifacts.addItem("")
        self.Artifacts.addItem("")
        self.Artifacts.addItem("")
        self.Artifacts.addItem("")

        self.SettingTime = QtWidgets.QLabel(Dialog)
        self.SettingTime.setGeometry(QtCore.QRect(30, 100, 120, 20))#"시간 설정"
        self.SettingTime.setFont(font1)
        self.SettingTime.setObjectName("SettingTime")

        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(290, 40, 360, 25))#검색기준3(문자열입력) 박스
        self.lineEdit.setObjectName("lineEdit")

        #ui.check()
        self.retranslateUi(Dialog)

        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Achu_test"))
        self.ListTable.setHorizontalHeaderLabels(["File Name", "File Path", "Last Run Time", "Size"])
        self.saveButton.setText(_translate("Dialog", "저장"))
        self.Category.setItemText(0, _translate("Dialog", "파일명"))
        self.Category.setItemText(1, _translate("Dialog", "생성 시간"))
        self.Category.setItemText(2, _translate("Dialog", "수정 시간"))
        self.Category.setItemText(3, _translate("Dialog", "실행 시간"))
        self.Category.setItemText(4, _translate("Dialog", "URL"))
        self.Category.setItemText(5, _translate("Dialog", "다운 로드"))
        self.SettingTime_2.setText(_translate("Dialog", "파일 크기(KB)"))
        self.SettingTime2.setText(_translate("Dialog", "~"))
        self.SearchButton.setText(_translate("Dialog", "Search"))
        self.Artifacts.setItemText(0, _translate("Dialog", "Artifacts"))
        self.Artifacts.setItemText(1, _translate("Dialog", "Prefetch"))
        self.Artifacts.setItemText(2, _translate("Dialog", "WebBrowser"))
        self.Artifacts.setItemText(3, _translate("Dialog", "LNK"))
        self.Artifacts.setItemText(4, _translate("Dialog", "ShimCache"))
        self.SettingTime.setText(_translate("Dialog", "시간 설정"))
        #self.FilePath_Label.setText(_translate("Dialog", "경로 설정"))
        ui.Defile()


    def Defile(self):
        check2()
        count = 0
        for i in realDeleted:
            self.ListTable.setItem(count, 0, QtWidgets.QTableWidgetItem(i[0]))
            self.ListTable.setItem(count, 1, QtWidgets.QTableWidgetItem(i[1]))
            self.ListTable.setItem(count, 2, QtWidgets.QTableWidgetItem(i[2]))
            self.ListTable.setItem(count, 3, QtWidgets.QTableWidgetItem(str(i[3])))
            count += 1
        return count


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
