# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinkFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, tab,tapname_list):
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setBold(False)
        font.setWeight(50)
        font.setPointSize(9)

        font1 = QtGui.QFont()
        font1.setFamily("Agency FB")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)

        self.gridLayout_5 = QtWidgets.QGridLayout(tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()

        self.Delete_Files = QtWidgets.QTableWidget(tab)
        self.gridLayout_5.addWidget(self.Delete_Files, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.Delete_Files.setObjectName("Delete_Files")
        self.Delete_Files.setFont(font)
        self.Delete_Files.setMouseTracking(False)
        self.Delete_Files.setTabletTracking(False)
        self.Delete_Files.setAcceptDrops(False)
        self.Delete_Files.setToolTipDuration(-1)
        self.Delete_Files.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Delete_Files.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)  # 가로스크롤
        self.Delete_Files.setAutoScroll(True)
        self.Delete_Files.setAutoScrollMargin(16)
        self.Delete_Files.setSortingEnabled(True)
        self.Delete_Files.setShowGrid(True)
        self.Delete_Files.setRowCount(1)
        self.Delete_Files.setColumnCount(4)
        self.Delete_Files.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)  # Options : Not Edit
        self.Delete_Files.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Delete_Files.setHorizontalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Delete_Files.setHorizontalHeaderItem(1, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        item.setFont(font)
        self.Delete_Files.setHorizontalHeaderItem(2, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Delete_Files.setHorizontalHeaderItem(3, item)

        self.Delete_Files.setHorizontalHeaderLabels(["File Name", "File Path", "Last Run Time", "Size"])
        tapname_list.append(self.Delete_Files.objectName())
        header = self.Delete_Files.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        for i in range(1, self.Delete_Files.columnCount() - 1):
            header.setSectionResizeMode(i, QtWidgets.QHeaderView.ResizeToContents)

    def update(self):
        self.Delete_Files.update()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog,"")
    Dialog.show()
    sys.exit(app.exec_())