# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinkFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, tab,tapname_list):

        self.gridLayout_5 = QtWidgets.QGridLayout(tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()

        self.Link_Detail = QtWidgets.QTableWidget(tab)
        self.gridLayout_5.addWidget(self.Link_Detail, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.Link_Detail.setRowCount(16)
        self.Link_Detail.setObjectName("Link_Detail")
        self.Link_Detail.setColumnCount(1)

        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.Link_Detail.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()

        tapname_list.append(self.Link_Detail.objectName())
        self.Link_Detail.setHorizontalHeaderItem(0, item)
        self.Link_Label = QtWidgets.QLabel(tab)
        self.Link_Detail.setVerticalHeaderLabels(
            ["파일 이름", "파일 크기", "생성 시간", "수정 시간", "실행 시간", "원본 파일 이름", "원본 파일 크기",
             "원본 생성 시간", "원본 수정 시간", "원본 삭제 시간", "원본 파일 경로", "드라이브 유형", "시리얼 번호",
             "현재 MAC 주소", "최초 MAC 주소", "NetBios"])
        self.Link_Detail.setHorizontalHeaderLabels(["데이터"])
        self.Link_Detail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Link_Detail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Link_Detail.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)  # Options : Not Edit
        self.Link_Detail.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)  # Select Rows
        self.Link_Detail.setAutoScroll(True)
        self.Link_Detail.setSortingEnabled(True)
        header = self.Link_Detail.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header_ver = self.Link_Detail.verticalHeader()
        for i in range(0, self.Link_Detail.rowCount()):
            header_ver.setSectionResizeMode(i, QtWidgets.QHeaderView.Stretch)

    def update(self):
        self.Link_Detail.update()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, "")
    Dialog.show()
    sys.exit(app.exec_())
