# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinkFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, tab,tapname_list):

        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setBold(False)
        font.setWeight(50)
        font.setPointSize(9)

        font1 = QtGui.QFont()
        font1.setFamily("Agency FB")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)

        self.gridLayout_5 = QtWidgets.QGridLayout(tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()

        self.Pre_Detail = QtWidgets.QTableWidget(tab)
        self.gridLayout_5.addWidget(self.Pre_Detail, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.Pre_Detail.setRowCount(16)
        self.Pre_Detail.setObjectName("Pre_Detail")
        self.Pre_Detail.setColumnCount(1)

        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.Pre_Detail.setColumnWidth(0, 350)

        self.Dll_list_Detail = QtWidgets.QTableWidget(tab)
        self.gridLayout_5.addWidget(self.Dll_list_Detail, 1, 0, 1, 1)
        self.Dll_list_Detail.setRowCount(0)
        self.Dll_list_Detail.setColumnCount(2)
        self.Dll_list_Detail.setObjectName("Dll_list_Detail")

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Dll_list_Detail.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Dll_list_Detail.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.Dll_list_Detail.setHorizontalHeaderItem(2, item)


        self.Dll_list_Detail.setHorizontalHeaderLabels(["File Name", "Full Path"])
        self.Dll_list_Detail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Dll_list_Detail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Dll_list_Detail.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)  # Options : Not Edit
        self.Dll_list_Detail.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)  # Select Rows
        self.Dll_list_Detail.setAutoScroll(True)
        self.Dll_list_Detail.setSortingEnabled(True)
        header = self.Dll_list_Detail.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)


        self.Pre_Detail.setVerticalHeaderLabels(["파일 이름","생성 시각", "수정 시각", "파일 크기", "실행 파일 이름", "실행 파일 경로","실행 횟수","최초 실행 시각",
                                                 "실행 기록_1","실행 기록_2","실행 기록_3","실행 기록_4","실행 기록_5","실행 기록_6","마지막 실행 시각","버전",])
        self.Pre_Detail.setHorizontalHeaderLabels(["데이터"])
        self.Pre_Detail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Pre_Detail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Pre_Detail.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)  # Options : Not Edit
        self.Pre_Detail.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)  # Select Rows
        self.Pre_Detail.setAutoScroll(True)
        self.Pre_Detail.setSortingEnabled(True)
        header = self.Pre_Detail.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header_ver = self.Pre_Detail.verticalHeader()
        for i in range(0, self.Pre_Detail.rowCount()):
            header_ver.setSectionResizeMode(i, QtWidgets.QHeaderView.Stretch)

        self.Dll_list_Detail.setRowCount(0)
        self.Dll_list_Detail.setRowCount(2)

        tapname_list.append(self.Pre_Detail.objectName())

    def update(self):
        self.Pre_Detail.update()
        self.Dll_list_Detail.update()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())