# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinkFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, number, tab, tapname_list):

        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setBold(False)
        font.setWeight(50)
        font.setPointSize(9)

        font1 = QtGui.QFont()
        font1.setFamily("Agency FB")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)

        self.gridLayout_5 = QtWidgets.QGridLayout(tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()

        self.SearchListTable = QtWidgets.QTableWidget(tab)
        self.gridLayout_5.addWidget(self.SearchListTable, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.SearchListTable.setFont(font)
        self.SearchListTable.setMouseTracking(True)
        self.SearchListTable.setTabletTracking(False)
        self.SearchListTable.setAcceptDrops(False)
        self.SearchListTable.setToolTipDuration(-1)
        self.SearchListTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.SearchListTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.SearchListTable.setAutoScroll(True)
        self.SearchListTable.setAutoScrollMargin(16)
        self.SearchListTable.setShowGrid(True) # Remove to Border
        self.SearchListTable.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers) # Options : Not Edit
        self.SearchListTable.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows) # Select Rows
        self.SearchListTable.setSortingEnabled(True)
        self.SearchListTable.setRowCount(number)
        self.SearchListTable.setColumnCount(6)
        self.SearchListTable.setObjectName("SearchListTable")

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.SearchListTable.setHorizontalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        item.setFont(font)
        self.SearchListTable.setHorizontalHeaderItem(1, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.SearchListTable.setHorizontalHeaderItem(2, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        item.setFont(font)
        self.SearchListTable.setHorizontalHeaderItem(3, item)

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignTop)
        item.setFont(font)
        self.SearchListTable.setHorizontalHeaderItem(4, item)
        self.SearchListTable.setColumnHidden(5, True)

        self.SearchListTable.setHorizontalHeaderLabels(["File Name", "Create Time", "Modified Time", "Run Time", "Artifact", ""])

        tapname_list.append(self.SearchListTable.objectName())
        self.SearchListTable.doubleClicked.connect(lambda: self.DoubleClick_Event(self.SearchListTable.objectName()))

        header = self.SearchListTable.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        for i in range(1, self.SearchListTable.columnCount() - 1):
            header.setSectionResizeMode(i, QtWidgets.QHeaderView.ResizeToContents)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
