# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LinkFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, tab,tapname_list):

        self.gridLayout_5 = QtWidgets.QGridLayout(tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()

        self.Shim_Detail = QtWidgets.QTableWidget(tab)
        self.gridLayout_5.addWidget(self.Shim_Detail, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.Shim_Detail.setRowCount(5)
        self.Shim_Detail.setObjectName("Shim_Detail")
        self.Shim_Detail.setColumnCount(1)

        item = QtWidgets.QTableWidgetItem()
        self.Shim_Detail.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Shim_Detail.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Shim_Detail.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Shim_Detail.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Shim_Detail.setVerticalHeaderItem(4, item)

        item = QtWidgets.QTableWidgetItem()
        self.Shim_Detail.setColumnWidth(0, 300)
        tapname_list.append(self.Shim_Detail.objectName())
        self.Shim_Detail.setHorizontalHeaderItem(0, item)
        self.Shim_Detail.setSortingEnabled(True)
        self.Shim_Detail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Shim_Detail.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Shim_Detail.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)  # Options : Not Edit
        self.Shim_Detail.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)  # Select Rows
        self.Shim_Detail.setAutoScroll(True)

        self.Shim_Detail.setVerticalHeaderLabels(
                ["실행 파일 이름","실행 파일 경로","마지막 수정 시각","마지막 실행 시각","참조 아티팩트 경로"])
        self.Shim_Detail.setHorizontalHeaderLabels(["데이터"])
        header = self.Shim_Detail.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header_ver = self.Shim_Detail.verticalHeader()
        for i in range(0, self.Shim_Detail.rowCount()):
            header_ver.setSectionResizeMode(i, QtWidgets.QHeaderView.Stretch)

    def update(self):
        self.Shim_Detail.update()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())