# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pro.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from tkinter import Tk
from tkinter import messagebox as msg
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QLabel


class Progress_Bar(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 395)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        # self.DialogBar = QtWidgets.QProgressBar(Dialog)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(220, 320, 64, 15))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        # self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.lbl = QLabel(Dialog)
        pixmap = QPixmap("./image/ACHU_logo2.png")
        self.lbl.setPixmap(QPixmap(pixmap))
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout_2.addWidget(self.lbl, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Achu Execution-related Artifact Extraction Analysis Tool"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/ACHU_logo6.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Progress_Bar()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())